### ISSUE TITLE
🔐Windows 환경에서 API KEY 정상등록되지 않음

### ISSUE THREAD

**Issue by seseun** [awesomelon/commitAI#1]
### 내용
- Windows 환경에서 설치는 정상적으로 됩니다🪄
- `commit-ai --key YOUR_API_KEY` 으로 Api Key 설정시 정상등록되지 않는 것 같습니다.
- 터미널을 재시작해서 시도해보거나, `yarn`, `npm` 으로 모두 시도하였습니다.
- node v.20.11.0

---
🐣`yarn`, `vscode gitbash terminal`

![image](https://github.com/user-attachments/assets/ee61ce8b-1ec7-4603-92f6-026bbf4e8df7)

---
🐣`npm`, `gitbash terminal`

![image](https://github.com/user-attachments/assets/d33c198c-bb18-4c7a-a0ff-768b1a7c5e1f)

**Comment by awesomelon** [comment]
해당 이슈 해결되었습니다 🎉

# v0.2.14
